build:
	@docker build -t vitorcostasilva/api-devops-challenge:1.0 .

run:
	@docker run -d -p 8085:8085 --name api-devops-challenge vitorcostasilva/api-devops-challenge:1.0

compose:
	@docker compose build
	@docker compose up