apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datapi

resources:
  - namespace.yaml
  - deployment.yaml
  - secret.yaml

commonLabels:
  app: datapi
  env: dev
  version: v1.0
