name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/fsharp-app:latest -f projeto-fsharp/Dockerfile .
        docker push ghcr.io/${{ github.repository_owner }}/fsharp-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v2
      with:
        version: 'v1.21.0'

    - name: Deploy to Kubernetes
      run: kubectl apply -f deploy.yml
