name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t docker.io/yurilinc/fsharp-app:latest .

    - name: Push Docker image
      run: docker push docker.io/yurilinc/fsharp-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v2
      with:
        version: 'v1.21.0'

    - name: Deploy to Kubernetes
      run: kubectl apply -f deploy.yml
