# This is a basic workflow to help you get started with Actions

name: Build and Push Image platform ARM

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     arch: [arm64]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Realizando checkout do repositório
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: projeto-fsharp
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/vitor-csilva/api-devops-challenge:latest
