name: 'Provision Azure'

on:
  push:
    branches: [ "master","develop" ]
    paths:
      - terraform/**

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest   
    defaults:
      run:
        working-directory: terraform

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve