# This is a basic workflow to help you get started with Actions

name: Build and Push Image platform ARM

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Realizando checkout do repositório
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker@v2

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      
      - name: Log in no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: Build e push Docker image
      #   run: |
      #     cd projeto-fsharp
      #     docker build . --tag ghcr.io/vitor-csilva/api-devops-challenge:arm
      #     docker push ghcr.io/vitor-csilva/api-devops-challenge:arm
          
      - name: Build e push Docker image
        run: |
          cd projeto-fsharp
          docker buildx create --name mybuilder
          docker buildx use mybuilder
          docker buildx build --platform linux/arm64 -t ghcr.io/vitor-csilva/api-devops-challenge:arm .
          docker push ghcr.io/vitor-csilva/api-devops-challenge:arm
