name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Build Docker Image
      runs: |
        docker build -t docker-image .
    
    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Push to Registry
      run: |
        IMAGE_NAME="${{ vars.REGISTRY }}/${{ vars.PROJECT_NAME }}"
        docker tag docker-image:latest $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest
