name: build-and-publish-container-image

on: [workflow_dispatch]

jobs:
  build-and-publish-container-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and tag Docker image
      run: |
        short_commit=$(git rev-parse --short HEAD)
        cd projeto-fsharp
        docker build . -t ghcr.io/richardneves/projeto-fsharp:latest -t ghcr.io/richardneves/projeto-fsharp:${short_commit}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}

    - name: Push Docker image
      run: |
        short_commit=$(git rev-parse --short HEAD)
        docker push ghcr.io/richardneves/projeto-fsharp:${short_commit}
        docker push ghcr.io/richardneves/projeto-fsharp:latest
