name: Terraform Plan

on:
  pull_request:
    paths:
      - 'infraservices/terras/**'

jobs:
  plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0 # Atualize para a versão desejada

    - name: Terraform Init
      run: terraform init
      working-directory: infraservices/terras

    - name: Terraform Plan
      run: terraform plan
      working-directory: infraservices/terras
      env:
        DEBUG: true
