name: Terraform Plan

on:
  push: # test
    branches:
      - main
      - master

jobs:
  plan-dev:
    name: 'Terraform plan DEV'
    runs-on: 'ubuntu-latest'

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0
      
      - name: Terraform Plan
        run: |
          cd terraform
          terraform init
          terraform plan
        working-directory: terraform
